import { StyleSheet } from "react-native";
import type { AppColors } from "../../constants/colors";

export const createAddFriendStyles = (colors: AppColors) =>
  StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: colors.background,
    },
    container: {
      flex: 1,
      position: "relative",
    },
    glowOrbTop: {
      position: "absolute",
      top: -110,
      left: -80,
      width: 260,
      height: 260,
      borderRadius: 999,
      backgroundColor: colors.primaryLight,
      opacity: 0.8,
    },
    glowOrbBottom: {
      position: "absolute",
      bottom: -130,
      right: -70,
      width: 280,
      height: 280,
      borderRadius: 999,
      backgroundColor: colors.primaryLight,
      opacity: 0.6,
    },
    header: {
      marginHorizontal: 20,
      marginTop: 20,
      marginBottom: 20,
      paddingHorizontal: 24,
      paddingVertical: 24,
      borderRadius: 32,
      backgroundColor: colors.surface,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.05,
      shadowRadius: 20,
      elevation: 7,
    },
    kicker: {
      fontSize: 12,
      fontWeight: "800",
      letterSpacing: 1.2,
      textTransform: "uppercase",
      color: colors.primary,
      marginBottom: 6,
    },
    title: {
      fontSize: 32,
      fontWeight: "900",
      color: colors.text,
      marginBottom: 4,
    },
    subtitle: {
      fontSize: 14,
      lineHeight: 20,
      color: colors.secondaryText,
      fontWeight: "500",
    },
    searchInput: {
      marginHorizontal: 20,
      marginBottom: 16,
      borderRadius: 20,
      paddingHorizontal: 16,
      paddingVertical: 14,
      backgroundColor: colors.surface,
      color: colors.text,
      fontSize: 15,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.04,
      shadowRadius: 10,
      elevation: 2,
    },
    searchInputTight: {
      marginHorizontal: 0,
      marginBottom: 0,
      flex: 1,
    },
    searchRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      marginHorizontal: 20,
      marginBottom: 16,
    },
    searchButton: {
      borderRadius: 20,
      backgroundColor: colors.primary,
      paddingHorizontal: 24,
      paddingVertical: 14,
      minWidth: 90,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
      elevation: 4,
    },
    searchButtonText: {
      color: "#FFFFFF",
      fontWeight: "800",
      fontSize: 14,
      letterSpacing: 0.3,
    },
    loadingState: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
    },
    scrollContainer: {
      flexGrow: 1,
      paddingBottom: 40,
    },
    listContainer: {
      paddingHorizontal: 20,
    },
    sectionCard: {
      borderRadius: 24,
      backgroundColor: colors.surface,
      paddingHorizontal: 16,
      paddingVertical: 16,
      marginBottom: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.04,
      shadowRadius: 12,
      elevation: 4,
    },
    resultCard: {
      borderRadius: 20,
      backgroundColor: colors.background,
      paddingHorizontal: 16,
      paddingVertical: 14,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 12,
      gap: 12,
    },
    resultName: {
      color: colors.text,
      fontSize: 16,
      fontWeight: "800",
    },
    resultMeta: {
      color: colors.secondaryText,
      fontSize: 13,
      marginTop: 4,
      fontWeight: "500",
    },
    sectionTitle: {
      color: colors.primary,
      fontSize: 12,
      textTransform: "uppercase",
      letterSpacing: 1.2,
      marginBottom: 12,
      fontWeight: "800",
    },
    requestRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      borderRadius: 20,
      backgroundColor: colors.background,
      paddingVertical: 14,
      paddingHorizontal: 14,
      marginBottom: 10,
      gap: 12,
    },
    requestName: {
      color: colors.text,
      fontSize: 15,
      fontWeight: "800",
    },
    requestMeta: {
      color: colors.secondaryText,
      fontSize: 13,
      marginTop: 3,
      fontWeight: "500",
    },
    primaryButton: {
      borderRadius: 999,
      backgroundColor: colors.primary,
      paddingHorizontal: 20,
      paddingVertical: 10,
      minWidth: 90,
      alignItems: "center",
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 3,
    },
    primaryButtonText: {
      color: "#FFFFFF",
      fontSize: 13,
      fontWeight: "800",
    },
    cancelButton: {
      borderRadius: 999,
      backgroundColor: colors.error,
      paddingHorizontal: 16,
      paddingVertical: 10,
      minWidth: 80,
      alignItems: "center",
      shadowColor: colors.error,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 3,
    },
    cancelButtonText: {
      color: "#FFFFFF",
      fontSize: 13,
      fontWeight: "800",
    },
    buttonDisabled: {
      opacity: 0.5,
    },
    emptyState: {
      paddingHorizontal: 20,
      paddingTop: 48,
      alignItems: "center",
    },
    emptyStateCompact: {
      borderRadius: 20,
      backgroundColor: colors.background,
      paddingVertical: 24,
      paddingHorizontal: 16,
      alignItems: "center",
      marginBottom: 12,
    },
    emptyText: {
      fontSize: 15,
      color: colors.secondaryText,
      textAlign: "center",
      lineHeight: 22,
      fontWeight: "500",
    },
  });

export default createAddFriendStyles;
