import { StyleSheet } from "react-native";
import type { AppColors } from "../../constants/colors";

export const createAddFriendStyles = (colors: AppColors) =>
  StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: colors.background,
    },
    container: {
      flex: 1,
      position: "relative",
    },
    glowOrbTop: {
      position: "absolute",
      top: -110,
      left: -80,
      width: 260,
      height: 260,
      borderRadius: 999,
      backgroundColor: "rgba(37, 99, 235, 0.20)",
    },
    glowOrbBottom: {
      position: "absolute",
      bottom: -130,
      right: -70,
      width: 280,
      height: 280,
      borderRadius: 999,
      backgroundColor: "rgba(16, 185, 129, 0.16)",
    },
    header: {
      marginHorizontal: 14,
      marginTop: 10,
      marginBottom: 14,
      paddingHorizontal: 18,
      paddingVertical: 18,
      borderRadius: 26,
      backgroundColor: colors.surface,
      borderWidth: 1.5,
      borderColor: "rgba(37, 99, 235, 0.22)",
      shadowColor: "#0b3b8f",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.2,
      shadowRadius: 18,
      elevation: 7,
    },
    kicker: {
      fontSize: 11,
      fontWeight: "800",
      letterSpacing: 1.2,
      textTransform: "uppercase",
      color: "#0ea5e9",
      marginBottom: 5,
    },
    title: {
      fontSize: 32,
      fontWeight: "900",
      color: colors.text,
      marginBottom: 2,
    },
    subtitle: {
      fontSize: 13,
      lineHeight: 18,
      color: colors.secondaryText,
      fontWeight: "500",
    },
    searchInput: {
      marginHorizontal: 14,
      marginBottom: 12,
      borderRadius: 16,
      paddingHorizontal: 14,
      paddingVertical: 12,
      backgroundColor: colors.surface,
      borderWidth: 1.5,
      borderColor: "rgba(37, 99, 235, 0.22)",
      color: colors.text,
      fontSize: 14,
      shadowColor: "#0f172a",
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 1,
    },
    searchInputTight: {
      marginHorizontal: 0,
      marginBottom: 0,
      flex: 1,
    },
    searchRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginHorizontal: 14,
      marginBottom: 12,
    },
    searchButton: {
      borderRadius: 14,
      backgroundColor: colors.primary,
      paddingHorizontal: 20,
      paddingVertical: 12,
      minWidth: 84,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: "rgba(255, 255, 255, 0.20)",
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.32,
      shadowRadius: 14,
      elevation: 5,
    },
    searchButtonText: {
      color: colors.primaryText,
      fontWeight: "800",
      fontSize: 13,
      letterSpacing: 0.3,
    },
    loadingState: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
    },
    listContainer: {
      paddingHorizontal: 14,
      paddingBottom: 28,
    },
    sectionCard: {
      borderRadius: 22,
      borderWidth: 1,
      borderColor: "rgba(37, 99, 235, 0.16)",
      backgroundColor: colors.surface,
      paddingHorizontal: 14,
      paddingVertical: 14,
      marginBottom: 14,
      shadowColor: "#0f172a",
      shadowOffset: { width: 0, height: 7 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 4,
    },
    resultCard: {
      borderWidth: 1,
      borderColor: "rgba(37, 99, 235, 0.18)",
      borderRadius: 16,
      backgroundColor: colors.background,
      paddingHorizontal: 13,
      paddingVertical: 12,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 10,
      gap: 10,
    },
    resultName: {
      color: colors.text,
      fontSize: 15,
      fontWeight: "800",
    },
    resultMeta: {
      color: colors.secondaryText,
      fontSize: 12,
      marginTop: 3,
    },
    sectionTitle: {
      color: colors.primary,
      fontSize: 11,
      textTransform: "uppercase",
      letterSpacing: 1.2,
      marginBottom: 10,
      fontWeight: "800",
    },
    requestRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      borderWidth: 1,
      borderColor: "rgba(16, 185, 129, 0.20)",
      borderRadius: 16,
      backgroundColor: colors.background,
      paddingVertical: 11,
      paddingHorizontal: 12,
      marginBottom: 9,
      gap: 10,
    },
    requestName: {
      color: colors.text,
      fontSize: 14,
      fontWeight: "700",
    },
    requestMeta: {
      color: colors.secondaryText,
      fontSize: 12,
      marginTop: 2,
    },
    primaryButton: {
      borderRadius: 999,
      backgroundColor: colors.primary,
      paddingHorizontal: 18,
      paddingVertical: 8,
      minWidth: 82,
      alignItems: "center",
      borderWidth: 1,
      borderColor: "rgba(255, 255, 255, 0.24)",
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.25,
      shadowRadius: 10,
      elevation: 3,
    },
    primaryButtonText: {
      color: colors.primaryText,
      fontSize: 12,
      fontWeight: "800",
    },
    cancelButton: {
      borderRadius: 999,
      backgroundColor: colors.buttonDanger ?? colors.error,
      paddingHorizontal: 14,
      paddingVertical: 8,
      minWidth: 72,
      alignItems: "center",
      borderWidth: 1,
      borderColor: "rgba(255, 255, 255, 0.22)",
      shadowColor: colors.buttonDanger ?? colors.error,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 2,
    },
    cancelButtonText: {
      color: colors.primaryText,
      fontSize: 12,
      fontWeight: "800",
    },
    buttonDisabled: {
      opacity: 0.55,
    },
    emptyState: {
      paddingHorizontal: 16,
      paddingTop: 48,
      alignItems: "center",
    },
    emptyStateCompact: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 16,
      backgroundColor: colors.background,
      paddingVertical: 18,
      paddingHorizontal: 14,
      alignItems: "center",
      marginBottom: 10,
    },
    emptyText: {
      fontSize: 14,
      color: colors.secondaryText,
      textAlign: "center",
      lineHeight: 19,
    },
  });

export default createAddFriendStyles;
