import { StyleSheet } from "react-native";
import type { AppColors } from "../../constants/colors";

export const createAddFriendStyles = (colors: AppColors) =>
  StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: colors.background,
    },
    container: {
      flex: 1,
      position: "relative",
    },
    glowOrbTop: {
      position: "absolute",
      top: -90,
      left: -70,
      width: 220,
      height: 220,
      borderRadius: 999,
      backgroundColor: "rgba(59, 130, 246, 0.14)",
    },
    glowOrbBottom: {
      position: "absolute",
      bottom: -120,
      right: -60,
      width: 240,
      height: 240,
      borderRadius: 999,
      backgroundColor: "rgba(16, 185, 129, 0.12)",
    },
    header: {
      marginHorizontal: 16,
      marginTop: 12,
      marginBottom: 12,
      paddingHorizontal: 16,
      paddingVertical: 16,
      borderRadius: 22,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: "#111827",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 14,
      elevation: 5,
    },
    kicker: {
      fontSize: 11,
      fontWeight: "800",
      letterSpacing: 1,
      textTransform: "uppercase",
      color: colors.primary,
      marginBottom: 4,
    },
    title: {
      fontSize: 30,
      fontWeight: "800",
      color: colors.text,
      marginBottom: 2,
    },
    subtitle: {
      fontSize: 13,
      color: colors.secondaryText,
      fontWeight: "500",
    },
    searchInput: {
      marginHorizontal: 16,
      marginBottom: 12,
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 11,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      color: colors.text,
    },
    searchInputTight: {
      marginHorizontal: 0,
      marginBottom: 0,
      flex: 1,
    },
    searchRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginHorizontal: 16,
      marginBottom: 12,
    },
    searchButton: {
      borderRadius: 12,
      backgroundColor: colors.primary,
      paddingHorizontal: 18,
      paddingVertical: 11,
      minWidth: 76,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.25,
      shadowRadius: 12,
      elevation: 4,
    },
    searchButtonText: {
      color: colors.primaryText,
      fontWeight: "700",
      fontSize: 13,
    },
    loadingState: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
    },
    listContainer: {
      paddingHorizontal: 16,
      paddingBottom: 26,
    },
    sectionCard: {
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      paddingHorizontal: 12,
      paddingVertical: 12,
      marginBottom: 14,
      shadowColor: "#0f172a",
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.08,
      shadowRadius: 10,
      elevation: 3,
    },
    resultCard: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      backgroundColor: colors.background,
      paddingHorizontal: 12,
      paddingVertical: 11,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 9,
      gap: 8,
    },
    resultName: {
      color: colors.text,
      fontSize: 15,
      fontWeight: "700",
    },
    resultMeta: {
      color: colors.secondaryText,
      fontSize: 12,
      marginTop: 2,
    },
    sectionTitle: {
      color: colors.secondaryText,
      fontSize: 12,
      textTransform: "uppercase",
      letterSpacing: 1,
      marginBottom: 8,
      fontWeight: "700",
    },
    requestRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      backgroundColor: colors.background,
      paddingVertical: 10,
      paddingHorizontal: 11,
      marginBottom: 8,
      gap: 10,
    },
    requestName: {
      color: colors.text,
      fontSize: 14,
      fontWeight: "700",
    },
    requestMeta: {
      color: colors.secondaryText,
      fontSize: 12,
      marginTop: 2,
    },
    primaryButton: {
      borderRadius: 999,
      backgroundColor: colors.primary,
      paddingHorizontal: 16,
      paddingVertical: 8,
      minWidth: 76,
      alignItems: "center",
    },
    primaryButtonText: {
      color: colors.primaryText,
      fontSize: 12,
      fontWeight: "700",
    },
    cancelButton: {
      borderRadius: 999,
      backgroundColor: colors.buttonDanger ?? colors.error,
      paddingHorizontal: 12,
      paddingVertical: 8,
      minWidth: 68,
      alignItems: "center",
    },
    cancelButtonText: {
      color: colors.primaryText,
      fontSize: 12,
      fontWeight: "700",
    },
    buttonDisabled: {
      opacity: 0.5,
    },
    emptyState: {
      paddingHorizontal: 16,
      paddingTop: 40,
      alignItems: "center",
    },
    emptyStateCompact: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      backgroundColor: colors.background,
      paddingVertical: 16,
      paddingHorizontal: 12,
      alignItems: "center",
      marginBottom: 10,
    },
    emptyText: {
      fontSize: 14,
      color: colors.secondaryText,
      textAlign: "center",
    },
  });

export default createAddFriendStyles;
