import { StyleSheet } from "react-native";
import type { AppColors } from "../../constants/colors";

export const createBlockedListStyles = (colors: AppColors) =>
  StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: colors.background,
    },
    container: {
      flex: 1,
      position: "relative",
    },
    glowOrbTop: {
      position: "absolute",
      top: -100,
      right: -65,
      width: 230,
      height: 230,
      borderRadius: 999,
      backgroundColor: "rgba(244, 63, 94, 0.14)",
    },
    glowOrbBottom: {
      position: "absolute",
      bottom: -120,
      left: -70,
      width: 240,
      height: 240,
      borderRadius: 999,
      backgroundColor: "rgba(37, 99, 235, 0.12)",
    },
    header: {
      marginHorizontal: 16,
      marginTop: 12,
      marginBottom: 14,
      paddingHorizontal: 16,
      paddingVertical: 16,
      borderRadius: 22,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: "#0f172a",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 14,
      elevation: 5,
    },
    kicker: {
      fontSize: 11,
      fontWeight: "800",
      letterSpacing: 1,
      textTransform: "uppercase",
      color: colors.buttonDanger ?? colors.error,
      marginBottom: 4,
    },
    title: {
      fontSize: 30,
      fontWeight: "800",
      color: colors.text,
    },
    subtitle: {
      marginTop: 4,
      fontSize: 13,
      color: colors.secondaryText,
      fontWeight: "500",
    },
    listContainer: {
      paddingHorizontal: 16,
      paddingBottom: 26,
    },
    sectionCard: {
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      paddingHorizontal: 12,
      paddingVertical: 12,
      shadowColor: "#0f172a",
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.08,
      shadowRadius: 10,
      elevation: 3,
    },
    sectionHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 8,
    },
    sectionLabel: {
      fontSize: 12,
      fontWeight: "700",
      color: colors.secondaryText,
      textTransform: "uppercase",
      letterSpacing: 1,
    },
    sectionCount: {
      backgroundColor: colors.buttonDanger ?? colors.error,
      color: colors.primaryText,
      fontSize: 11,
      fontWeight: "700",
      minWidth: 24,
      textAlign: "center",
      paddingVertical: 4,
      paddingHorizontal: 8,
      borderRadius: 999,
    },
    loadingState: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
    },
    emptyState: {
      paddingHorizontal: 16,
      paddingTop: 40,
      alignItems: "center",
    },
    emptyText: {
      fontSize: 14,
      color: colors.secondaryText,
      textAlign: "center",
    },
  });

export default createBlockedListStyles;
