import { StyleSheet } from "react-native";
import type { AppColors } from "../../constants/colors";

export const createBlockedListStyles = (colors: AppColors) =>
  StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: colors.background,
    },
    container: {
      flex: 1,
      position: "relative",
    },
    glowOrbTop: {
      position: "absolute",
      top: -115,
      right: -75,
      width: 270,
      height: 270,
      borderRadius: 999,
      backgroundColor: "rgba(244, 63, 94, 0.20)",
    },
    glowOrbBottom: {
      position: "absolute",
      bottom: -130,
      left: -80,
      width: 280,
      height: 280,
      borderRadius: 999,
      backgroundColor: "rgba(37, 99, 235, 0.16)",
    },
    header: {
      marginHorizontal: 14,
      marginTop: 10,
      marginBottom: 14,
      paddingHorizontal: 18,
      paddingVertical: 18,
      borderRadius: 26,
      backgroundColor: colors.surface,
      borderWidth: 1.5,
      borderColor: "rgba(244, 63, 94, 0.24)",
      shadowColor: "#831843",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.18,
      shadowRadius: 18,
      elevation: 7,
    },
    kicker: {
      fontSize: 11,
      fontWeight: "800",
      letterSpacing: 1.2,
      textTransform: "uppercase",
      color: colors.buttonDanger ?? colors.error,
      marginBottom: 5,
    },
    title: {
      fontSize: 32,
      fontWeight: "900",
      color: colors.text,
    },
    subtitle: {
      marginTop: 5,
      fontSize: 13,
      lineHeight: 18,
      color: colors.secondaryText,
      fontWeight: "500",
    },
    listContainer: {
      paddingHorizontal: 14,
      paddingBottom: 28,
    },
    sectionCard: {
      borderRadius: 22,
      borderWidth: 1,
      borderColor: "rgba(244, 63, 94, 0.20)",
      backgroundColor: colors.surface,
      paddingHorizontal: 14,
      paddingVertical: 14,
      shadowColor: "#0f172a",
      shadowOffset: { width: 0, height: 7 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 4,
    },
    sectionHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 10,
    },
    sectionLabel: {
      fontSize: 11,
      fontWeight: "800",
      color: colors.secondaryText,
      textTransform: "uppercase",
      letterSpacing: 1.15,
    },
    sectionCount: {
      backgroundColor: colors.buttonDanger ?? colors.error,
      color: colors.primaryText,
      fontSize: 11,
      fontWeight: "800",
      minWidth: 26,
      textAlign: "center",
      paddingVertical: 4,
      paddingHorizontal: 9,
      borderRadius: 999,
    },
    loadingState: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
    },
    emptyState: {
      paddingHorizontal: 16,
      paddingTop: 48,
      alignItems: "center",
    },
    emptyText: {
      fontSize: 14,
      color: colors.secondaryText,
      textAlign: "center",
      lineHeight: 19,
    },
  });

export default createBlockedListStyles;
