import { StyleSheet } from "react-native";
import type { AppColors } from "../../constants/colors";

export const createFriendsListStyles = (colors: AppColors) =>
  StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: colors.background,
    },
    container: {
      flex: 1,
      position: "relative",
    },
    glowOrbTop: {
      position: "absolute",
      top: -100,
      right: -50,
      width: 220,
      height: 220,
      borderRadius: 999,
      backgroundColor: "rgba(37, 99, 235, 0.16)",
    },
    glowOrbBottom: {
      position: "absolute",
      bottom: -120,
      left: -70,
      width: 240,
      height: 240,
      borderRadius: 999,
      backgroundColor: "rgba(16, 185, 129, 0.12)",
    },
    header: {
      marginHorizontal: 16,
      marginTop: 12,
      marginBottom: 14,
      paddingHorizontal: 16,
      paddingVertical: 16,
      borderRadius: 22,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      shadowColor: "#0b1220",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.14,
      shadowRadius: 16,
      elevation: 5,
    },
    kicker: {
      fontSize: 11,
      fontWeight: "700",
      textTransform: "uppercase",
      letterSpacing: 1,
      color: colors.primary,
      marginBottom: 2,
    },
    title: {
      fontSize: 30,
      fontWeight: "800",
      color: colors.text,
    },
    subtitle: {
      marginTop: 4,
      fontSize: 13,
      color: colors.secondaryText,
      fontWeight: "500",
    },
    headerActions: {
      flexDirection: "row",
      alignItems: "center",
      paddingTop: 4,
      gap: 8,
    },
    headerActionButton: {
      minWidth: 74,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: colors.primary,
      borderWidth: 1,
      borderColor: colors.primary,
    },
    headerActionText: {
      fontSize: 12,
      color: colors.primaryText,
      fontWeight: "700",
    },
    listContainer: {
      paddingHorizontal: 16,
      paddingBottom: 26,
    },
    loadingState: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
    },
    sectionCard: {
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      paddingHorizontal: 12,
      paddingVertical: 12,
      marginBottom: 14,
      shadowColor: "#0f172a",
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.08,
      shadowRadius: 10,
      elevation: 3,
    },
    sectionHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 8,
    },
    sectionLabel: {
      fontSize: 12,
      fontWeight: "700",
      color: colors.secondaryText,
      textTransform: "uppercase",
      letterSpacing: 1,
    },
    sectionCount: {
      backgroundColor: colors.primary,
      color: colors.primaryText,
      fontSize: 11,
      fontWeight: "700",
      minWidth: 24,
      textAlign: "center",
      paddingVertical: 4,
      paddingHorizontal: 8,
      borderRadius: 999,
    },
    emptyState: {
      paddingHorizontal: 20,
      paddingTop: 40,
      alignItems: "center",
    },
    emptyTitle: {
      fontSize: 16,
      fontWeight: "600",
      color: colors.text,
      marginBottom: 6,
    },
    emptySubtitle: {
      fontSize: 14,
      color: colors.secondaryText,
      textAlign: "center",
    },
    emptyInlineState: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      paddingVertical: 16,
      paddingHorizontal: 12,
      backgroundColor: colors.background,
    },
    retryButton: {
      marginTop: 14,
      borderRadius: 999,
      backgroundColor: colors.primary,
      paddingHorizontal: 16,
      paddingVertical: 9,
    },
    retryButtonText: {
      color: colors.primaryText,
      fontSize: 13,
      fontWeight: "700",
    },
    requestRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      backgroundColor: colors.background,
      paddingVertical: 10,
      paddingHorizontal: 10,
      marginBottom: 8,
      gap: 12,
    },
    requestLeft: {
      flexDirection: "row",
      alignItems: "center",
      flex: 1,
    },
    requestAvatar: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: "rgba(37, 99, 235, 0.12)",
      borderWidth: 1,
      borderColor: "rgba(37, 99, 235, 0.24)",
      alignItems: "center",
      justifyContent: "center",
      marginRight: 10,
    },
    requestAvatarText: {
      fontSize: 13,
      color: colors.primary,
      fontWeight: "800",
    },
    requestName: {
      color: colors.text,
      fontWeight: "700",
      fontSize: 14,
    },
    requestMeta: {
      color: colors.secondaryText,
      fontSize: 12,
      marginTop: 2,
    },
    requestActions: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    acceptButton: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: colors.primary,
      minWidth: 74,
      alignItems: "center",
    },
    acceptButtonText: {
      color: colors.primaryText,
      fontSize: 12,
      fontWeight: "700",
    },
    blockButton: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: colors.buttonDanger ?? colors.error,
      minWidth: 66,
      alignItems: "center",
    },
    blockButtonText: {
      color: colors.primaryText,
      fontSize: 12,
      fontWeight: "700",
    },
    disabledButton: {
      opacity: 0.5,
    },
  });

export default createFriendsListStyles;
