import { StyleSheet } from "react-native";
import type { AppColors } from "../../constants/colors";

export const createFriendsListStyles = (colors: AppColors) =>
  StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: colors.background,
    },
    container: {
      flex: 1,
      position: "relative",
    },
    glowOrbTop: {
      position: "absolute",
      top: -115,
      right: -70,
      width: 270,
      height: 270,
      borderRadius: 999,
      backgroundColor: "rgba(37, 99, 235, 0.20)",
    },
    glowOrbBottom: {
      position: "absolute",
      bottom: -130,
      left: -80,
      width: 280,
      height: 280,
      borderRadius: 999,
      backgroundColor: "rgba(16, 185, 129, 0.16)",
    },
    header: {
      marginHorizontal: 14,
      marginTop: 10,
      marginBottom: 14,
      paddingHorizontal: 18,
      paddingVertical: 18,
      borderRadius: 26,
      backgroundColor: colors.surface,
      borderWidth: 1.5,
      borderColor: "rgba(37, 99, 235, 0.22)",
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      shadowColor: "#0b3b8f",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.2,
      shadowRadius: 18,
      elevation: 7,
    },
    kicker: {
      fontSize: 11,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 1.2,
      color: "#0ea5e9",
      marginBottom: 4,
    },
    title: {
      fontSize: 32,
      fontWeight: "900",
      color: colors.text,
    },
    subtitle: {
      marginTop: 5,
      fontSize: 13,
      lineHeight: 18,
      color: colors.secondaryText,
      fontWeight: "500",
    },
    headerActions: {
      flexDirection: "row",
      alignItems: "center",
      paddingTop: 6,
      gap: 8,
    },
    headerActionButton: {
      minWidth: 80,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 14,
      paddingVertical: 9,
      borderRadius: 999,
      backgroundColor: colors.primary,
      borderWidth: 1,
      borderColor: "rgba(255, 255, 255, 0.24)",
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.24,
      shadowRadius: 10,
      elevation: 3,
    },
    headerActionText: {
      fontSize: 12,
      color: colors.primaryText,
      fontWeight: "800",
      letterSpacing: 0.3,
    },
    listContainer: {
      paddingHorizontal: 14,
      paddingBottom: 28,
    },
    loadingState: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
    },
    sectionCard: {
      borderRadius: 22,
      borderWidth: 1,
      borderColor: "rgba(37, 99, 235, 0.16)",
      backgroundColor: colors.surface,
      paddingHorizontal: 14,
      paddingVertical: 14,
      marginBottom: 14,
      shadowColor: "#0f172a",
      shadowOffset: { width: 0, height: 7 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 4,
    },
    sectionHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 10,
    },
    sectionLabel: {
      fontSize: 11,
      fontWeight: "800",
      color: colors.secondaryText,
      textTransform: "uppercase",
      letterSpacing: 1.15,
    },
    sectionCount: {
      backgroundColor: colors.primary,
      color: colors.primaryText,
      fontSize: 11,
      fontWeight: "800",
      minWidth: 26,
      textAlign: "center",
      paddingVertical: 4,
      paddingHorizontal: 9,
      borderRadius: 999,
    },
    emptyState: {
      paddingHorizontal: 20,
      paddingTop: 40,
      alignItems: "center",
    },
    emptyTitle: {
      fontSize: 17,
      fontWeight: "700",
      color: colors.text,
      marginBottom: 6,
    },
    emptySubtitle: {
      fontSize: 14,
      color: colors.secondaryText,
      textAlign: "center",
      lineHeight: 20,
    },
    emptyInlineState: {
      borderWidth: 1,
      borderColor: "rgba(100, 116, 139, 0.22)",
      borderRadius: 16,
      paddingVertical: 18,
      paddingHorizontal: 14,
      backgroundColor: colors.background,
    },
    retryButton: {
      marginTop: 16,
      borderRadius: 999,
      backgroundColor: colors.primary,
      paddingHorizontal: 18,
      paddingVertical: 10,
      borderWidth: 1,
      borderColor: "rgba(255, 255, 255, 0.20)",
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.24,
      shadowRadius: 10,
      elevation: 3,
    },
    retryButtonText: {
      color: colors.primaryText,
      fontSize: 13,
      fontWeight: "800",
    },
    requestRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      borderWidth: 1,
      borderColor: "rgba(37, 99, 235, 0.18)",
      borderRadius: 16,
      backgroundColor: colors.background,
      paddingVertical: 11,
      paddingHorizontal: 11,
      marginBottom: 9,
      gap: 12,
    },
    requestLeft: {
      flexDirection: "row",
      alignItems: "center",
      flex: 1,
    },
    requestAvatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: "rgba(37, 99, 235, 0.15)",
      borderWidth: 1,
      borderColor: "rgba(37, 99, 235, 0.30)",
      alignItems: "center",
      justifyContent: "center",
      marginRight: 10,
    },
    requestAvatarText: {
      fontSize: 13,
      color: colors.primary,
      fontWeight: "800",
    },
    requestName: {
      color: colors.text,
      fontWeight: "700",
      fontSize: 14,
    },
    requestMeta: {
      color: colors.secondaryText,
      fontSize: 12,
      marginTop: 2,
    },
    requestActions: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    acceptButton: {
      paddingHorizontal: 13,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: colors.primary,
      minWidth: 78,
      alignItems: "center",
      borderWidth: 1,
      borderColor: "rgba(255, 255, 255, 0.24)",
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.22,
      shadowRadius: 9,
      elevation: 2,
    },
    acceptButtonText: {
      color: colors.primaryText,
      fontSize: 12,
      fontWeight: "800",
    },
    blockButton: {
      paddingHorizontal: 13,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: colors.buttonDanger ?? colors.error,
      minWidth: 70,
      alignItems: "center",
      borderWidth: 1,
      borderColor: "rgba(255, 255, 255, 0.22)",
      shadowColor: colors.buttonDanger ?? colors.error,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 2,
    },
    blockButtonText: {
      color: colors.primaryText,
      fontSize: 12,
      fontWeight: "800",
    },
    disabledButton: {
      opacity: 0.55,
    },
  });

export default createFriendsListStyles;
