import { StyleSheet } from 'react-native';
import type { AppColors } from '../../constants/colors';

export const createFriendsChatStyles = (colors: AppColors, isWideScreen: boolean) =>
  StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: colors.background,
    },
    container: {
      flex: 1,
      position: 'relative',
      paddingHorizontal: 14,
      paddingTop: 10,
      paddingBottom: 12,
    },
    glowTop: {
      position: 'absolute',
      right: -90,
      top: -110,
      width: 280,
      height: 280,
      borderRadius: 999,
      backgroundColor: 'rgba(37, 99, 235, 0.18)',
    },
    glowBottom: {
      position: 'absolute',
      left: -95,
      bottom: -125,
      width: 300,
      height: 300,
      borderRadius: 999,
      backgroundColor: 'rgba(16, 185, 129, 0.15)',
    },
    header: {
      borderRadius: 24,
      borderWidth: 1.5,
      borderColor: 'rgba(37, 99, 235, 0.24)',
      backgroundColor: colors.surface,
      paddingHorizontal: 16,
      paddingVertical: 14,
      marginBottom: 12,
      shadowColor: '#0F172A',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 14,
      elevation: 4,
    },
    headerTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    backButton: {
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.background,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    backButtonText: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '700',
    },
    headerTextWrap: {
      flex: 1,
    },
    kicker: {
      fontSize: 11,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 1,
      color: '#0EA5E9',
      marginBottom: 4,
    },
    title: {
      color: colors.text,
      fontSize: 24,
      fontWeight: '900',
    },
    subtitle: {
      color: colors.secondaryText,
      fontSize: 13,
      fontWeight: '500',
      marginTop: 3,
    },
    layoutRow: {
      flex: 1,
      flexDirection: isWideScreen ? 'row' : 'column',
      gap: 12,
    },
    sidebarPane: {
      flex: isWideScreen ? 0 : 1,
      width: isWideScreen ? 340 : '100%',
      minWidth: isWideScreen ? 300 : 0,
    },
    chatPane: {
      flex: 1,
      borderRadius: 28,
      borderWidth: 1,
      borderColor: 'rgba(37, 99, 235, 0.24)',
      backgroundColor: colors.surface,
      shadowColor: '#0F172A',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.1,
      shadowRadius: 14,
      elevation: 4,
      paddingHorizontal: 12,
      paddingTop: 12,
      paddingBottom: 8,
    },
    chatHeader: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: 'rgba(37, 99, 235, 0.24)',
      backgroundColor: 'rgba(37, 99, 235, 0.08)',
      paddingHorizontal: 10,
      paddingVertical: 10,
      marginBottom: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    chatHeaderMain: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
      gap: 10,
    },
    chatTitleWrap: {
      flex: 1,
    },
    chatTitle: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '800',
    },
    chatMeta: {
      color: colors.secondaryText,
      fontSize: 12,
      marginTop: 2,
      fontWeight: '500',
    },
    chatHeaderAction: {
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderWidth: 1,
      borderColor: 'rgba(37, 99, 235, 0.34)',
      backgroundColor: 'rgba(37, 99, 235, 0.1)',
    },
    chatHeaderActionText: {
      color: colors.primary,
      fontSize: 12,
      fontWeight: '800',
    },
    messagesList: {
      flex: 1,
    },
    messagesContent: {
      paddingTop: 4,
      paddingBottom: 8,
    },
    emptyChatState: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 18,
      borderWidth: 1,
      borderColor: 'rgba(148, 163, 184, 0.25)',
      backgroundColor: colors.background,
      paddingHorizontal: 16,
      paddingVertical: 22,
    },
    emptyChatTitle: {
      color: colors.text,
      fontSize: 17,
      fontWeight: '800',
      textAlign: 'center',
      marginBottom: 6,
    },
    emptyChatSubtitle: {
      color: colors.secondaryText,
      textAlign: 'center',
      fontSize: 13,
      lineHeight: 20,
    },
    loadingState: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    errorWrap: {
      marginTop: 12,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: 'rgba(239, 68, 68, 0.3)',
      backgroundColor: 'rgba(239, 68, 68, 0.08)',
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    errorText: {
      color: colors.error,
      fontSize: 13,
      fontWeight: '600',
      textAlign: 'center',
    },
  });

export default createFriendsChatStyles;
