import { StyleSheet } from "react-native";
import type { AppColors } from "../../constants/colors";

export const createFriendsListStyles = (colors: AppColors) =>
  StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: colors.background,
    },
    container: {
      flex: 1,
      position: "relative",
    },
    glowOrbTop: {
      position: "absolute",
      top: -115,
      right: -70,
      width: 270,
      height: 270,
      borderRadius: 999,
      backgroundColor: colors.primaryLight,
      opacity: 0.8,
    },
    glowOrbBottom: {
      position: "absolute",
      bottom: -130,
      left: -80,
      width: 280,
      height: 280,
      borderRadius: 999,
      backgroundColor: colors.primaryLight,
      opacity: 0.6,
    },
    header: {
      marginHorizontal: 20,
      marginTop: 20,
      marginBottom: 20,
      paddingHorizontal: 24,
      paddingVertical: 24,
      borderRadius: 32,
      backgroundColor: colors.surface,
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.05,
      shadowRadius: 20,
      elevation: 7,
    },
    kicker: {
      fontSize: 12,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 1.2,
      color: colors.primary,
      marginBottom: 6,
    },
    title: {
      fontSize: 32,
      fontWeight: "900",
      color: colors.text,
    },
    subtitle: {
      marginTop: 6,
      fontSize: 14,
      lineHeight: 20,
      color: colors.secondaryText,
      fontWeight: "500",
    },
    headerActions: {
      flexDirection: "row",
      alignItems: "center",
      paddingTop: 8,
      gap: 10,
    },
    headerActionButton: {
      minWidth: 90,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderRadius: 999,
      backgroundColor: colors.primary,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
      elevation: 4,
    },
    headerActionText: {
      fontSize: 13,
      color: "#FFFFFF",
      fontWeight: "800",
      letterSpacing: 0.3,
    },
    listContainer: {
      paddingHorizontal: 20,
      paddingBottom: 40,
    },
    loadingState: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
    },
    sectionCard: {
      borderRadius: 24,
      backgroundColor: colors.surface,
      paddingHorizontal: 16,
      paddingVertical: 16,
      marginBottom: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.04,
      shadowRadius: 12,
      elevation: 4,
    },
    sectionHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 12,
      paddingHorizontal: 4,
    },
    sectionLabel: {
      fontSize: 12,
      fontWeight: "800",
      color: colors.secondaryText,
      textTransform: "uppercase",
      letterSpacing: 1.2,
    },
    sectionCount: {
      backgroundColor: colors.primaryLight,
      color: colors.primaryDark,
      fontSize: 12,
      fontWeight: "800",
      minWidth: 28,
      textAlign: "center",
      paddingVertical: 4,
      paddingHorizontal: 10,
      borderRadius: 999,
    },
    emptyState: {
      paddingHorizontal: 20,
      paddingTop: 40,
      alignItems: "center",
    },
    emptyTitle: {
      fontSize: 18,
      fontWeight: "800",
      color: colors.text,
      marginBottom: 8,
    },
    emptySubtitle: {
      fontSize: 14,
      color: colors.secondaryText,
      textAlign: "center",
      lineHeight: 22,
    },
    emptyInlineState: {
      borderRadius: 20,
      paddingVertical: 24,
      paddingHorizontal: 16,
      backgroundColor: colors.background,
      alignItems: "center",
    },
    retryButton: {
      marginTop: 20,
      borderRadius: 999,
      backgroundColor: colors.primary,
      paddingHorizontal: 24,
      paddingVertical: 12,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
      elevation: 4,
    },
    retryButtonText: {
      color: "#FFFFFF",
      fontSize: 14,
      fontWeight: "800",
    },
    requestRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      borderRadius: 20,
      backgroundColor: colors.background,
      paddingVertical: 14,
      paddingHorizontal: 14,
      marginBottom: 10,
      gap: 12,
    },
    requestLeft: {
      flexDirection: "row",
      alignItems: "center",
      flex: 1,
    },
    requestAvatar: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: colors.primaryLight,
      alignItems: "center",
      justifyContent: "center",
      marginRight: 12,
    },
    requestAvatarText: {
      fontSize: 16,
      color: colors.primaryDark,
      fontWeight: "800",
    },
    requestName: {
      color: colors.text,
      fontWeight: "800",
      fontSize: 15,
    },
    requestMeta: {
      color: colors.secondaryText,
      fontSize: 13,
      marginTop: 3,
      fontWeight: "500",
    },
    requestActions: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    acceptButton: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 999,
      backgroundColor: colors.primary,
      minWidth: 80,
      alignItems: "center",
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 3,
    },
    acceptButtonText: {
      color: "#FFFFFF",
      fontSize: 13,
      fontWeight: "800",
    },
    blockButton: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 999,
      backgroundColor: colors.error,
      minWidth: 70,
      alignItems: "center",
      shadowColor: colors.error,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 3,
    },
    blockButtonText: {
      color: "#FFFFFF",
      fontSize: 13,
      fontWeight: "800",
    },
    disabledButton: {
      opacity: 0.5,
    },
  });

export default createFriendsListStyles;
