import { StyleSheet } from "react-native";
import type { AppColors } from "../../constants/colors";

export const createFriendsStyles = (colors: AppColors) =>
  StyleSheet.create({
    row: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: 12,
      paddingHorizontal: 12,
      borderRadius: 16,
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: "rgba(37, 99, 235, 0.18)",
      marginBottom: 9,
    },
    rowBorder: {
      shadowColor: "#0f172a",
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.1,
      shadowRadius: 10,
      elevation: 3,
    },
    left: {
      flexDirection: "row",
      alignItems: "center",
      flexShrink: 1,
    },
    avatar: {
      width: 46,
      height: 46,
      borderRadius: 23,
      backgroundColor: "rgba(37, 99, 235, 0.16)",
      borderWidth: 1,
      borderColor: "rgba(37, 99, 235, 0.32)",
      alignItems: "center",
      justifyContent: "center",
      marginRight: 12,
    },
    avatarText: {
      fontSize: 14,
      fontWeight: "800",
      color: colors.primary,
    },
    name: {
      fontSize: 15,
      color: colors.text,
      fontWeight: "700",
    },
    status: {
      fontSize: 12,
      color: colors.secondaryText,
      marginTop: 3,
      fontWeight: "500",
    },
    right: {
      flexDirection: "row",
      alignItems: "center",
    },
    menuButton: {
      paddingHorizontal: 10,
      paddingVertical: 7,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: "rgba(100, 116, 139, 0.25)",
      backgroundColor: colors.surface,
    },
    menuText: {
      fontSize: 16,
      color: colors.secondaryText,
    },
    primaryButton: {
      paddingHorizontal: 15,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: colors.primary,
      minWidth: 78,
      alignItems: "center",
      borderWidth: 1,
      borderColor: "rgba(255, 255, 255, 0.24)",
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.22,
      shadowRadius: 9,
      elevation: 2,
    },
    primaryButtonDisabled: {
      backgroundColor: colors.divider,
      borderColor: colors.divider,
      shadowOpacity: 0,
      elevation: 0,
    },
    primaryButtonText: {
      color: colors.primaryText,
      fontWeight: "800",
      fontSize: 12,
    },
    dangerButton: {
      paddingHorizontal: 13,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: colors.buttonDanger ?? colors.error,
      minWidth: 78,
      alignItems: "center",
      borderWidth: 1,
      borderColor: "rgba(255, 255, 255, 0.22)",
      shadowColor: colors.buttonDanger ?? colors.error,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 2,
    },
    dangerButtonText: {
      color: colors.primaryText,
      fontWeight: "800",
      fontSize: 12,
    },
  });

export default createFriendsStyles;
