# Generated by Django 5.2.11 on 2026-02-15 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0002_friendship_blocked_by_alter_friendship_accepted_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='blocked_By',
            new_name='blocked_by',
        ),
    ]
