# Generated by Django 5.2.11 on 2026-03-14 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0005_alter_friendship_accepted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={'ordering': ['-sent_at']},
        ),
    ]
