# Generated by Django 5.2.11 on 2026-03-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0006_alter_friendship_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
