import { StyleSheet } from 'react-native';

import type { AppColors } from '../../constants/colors';

const createStyles = (colors: AppColors) =>
  StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: colors.background,
    },
    container: {
      flex: 1,
      position: 'relative',
    },
    glowOrbTop: {
      position: 'absolute',
      top: -90,
      right: -60,
      width: 220,
      height: 220,
      borderRadius: 999,
      backgroundColor: 'rgba(37, 99, 235, 0.16)',
    },
    glowOrbBottom: {
      position: 'absolute',
      bottom: -140,
      left: -90,
      width: 260,
      height: 260,
      borderRadius: 999,
      backgroundColor: 'rgba(16, 185, 129, 0.14)',
    },
    headerCard: {
      marginHorizontal: 16,
      marginTop: 12,
      marginBottom: 12,
      paddingHorizontal: 14,
      paddingVertical: 14,
      borderRadius: 24,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      flexDirection: 'row',
      alignItems: 'center',
      shadowColor: '#0b1220',
      shadowOffset: { width: 0, height: 7 },
      shadowOpacity: 0.14,
      shadowRadius: 16,
      elevation: 4,
    },
    backButton: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
    },
    backButtonText: {
      fontSize: 24,
      color: colors.text,
      fontWeight: '700',
      marginTop: -2,
    },
    headerTextBlock: {
      flex: 1,
    },
    headerKicker: {
      fontSize: 11,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 1,
      color: colors.primary,
      marginBottom: 3,
    },
    headerTitle: {
      fontSize: 28,
      fontWeight: '800',
      color: colors.text,
    },
    headerSubtitle: {
      marginTop: 2,
      fontSize: 12,
      color: colors.secondaryText,
      fontWeight: '500',
      maxWidth: 170,
    },
    unreadCountBubble: {
      minWidth: 68,
      borderRadius: 18,
      paddingVertical: 8,
      paddingHorizontal: 10,
      backgroundColor: 'rgba(37, 99, 235, 0.10)',
      borderWidth: 1,
      borderColor: 'rgba(37, 99, 235, 0.25)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    unreadCountNumber: {
      fontSize: 22,
      lineHeight: 24,
      color: colors.primary,
      fontWeight: '800',
    },
    unreadCountLabel: {
      fontSize: 11,
      color: colors.secondaryText,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.6,
    },
    actionsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginHorizontal: 16,
      marginBottom: 10,
    },
    primaryActionButton: {
      flex: 1,
      borderRadius: 999,
      backgroundColor: colors.primary,
      paddingHorizontal: 14,
      paddingVertical: 11,
      borderWidth: 1,
      borderColor: colors.primary,
      marginRight: 10,
      alignItems: 'center',
    },
    primaryActionButtonText: {
      color: colors.primaryText,
      fontWeight: '700',
      fontSize: 13,
    },
    secondaryActionButton: {
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      paddingHorizontal: 14,
      paddingVertical: 11,
      alignItems: 'center',
      justifyContent: 'center',
    },
    secondaryActionButtonText: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '700',
    },
    listContent: {
      paddingHorizontal: 16,
      paddingBottom: 28,
    },
    emptyListContent: {
      flexGrow: 1,
      justifyContent: 'center',
    },
    notificationCard: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      paddingHorizontal: 14,
      paddingVertical: 13,
      marginBottom: 10,
      shadowColor: '#0f172a',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 10,
      elevation: 2,
    },
    notificationCardUnread: {
      borderColor: 'rgba(37, 99, 235, 0.35)',
      backgroundColor: 'rgba(37, 99, 235, 0.04)',
    },
    cardHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 10,
    },
    cardIdentityRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexShrink: 1,
    },
    avatarBubble: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: 'rgba(148, 163, 184, 0.16)',
      borderWidth: 1,
      borderColor: 'rgba(100, 116, 139, 0.26)',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
    },
    avatarBubbleUnread: {
      backgroundColor: 'rgba(16, 185, 129, 0.15)',
      borderColor: 'rgba(16, 185, 129, 0.35)',
    },
    avatarText: {
      color: colors.text,
      fontSize: 12,
      fontWeight: '800',
    },
    typePill: {
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 10,
      paddingVertical: 4,
      alignSelf: 'flex-start',
      backgroundColor: colors.background,
    },
    typePillText: {
      fontSize: 11,
      color: colors.secondaryText,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.7,
    },
    timestampText: {
      marginTop: 5,
      fontSize: 12,
      color: colors.secondaryText,
      fontWeight: '500',
    },
    statusBadge: {
      borderRadius: 999,
      borderWidth: 1,
      paddingHorizontal: 9,
      paddingVertical: 4,
      marginLeft: 8,
    },
    statusBadgeUnread: {
      borderColor: 'rgba(37, 99, 235, 0.32)',
      backgroundColor: 'rgba(37, 99, 235, 0.12)',
    },
    statusBadgeRead: {
      borderColor: 'rgba(100, 116, 139, 0.25)',
      backgroundColor: 'rgba(148, 163, 184, 0.12)',
    },
    statusBadgeText: {
      fontSize: 11,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.6,
    },
    statusBadgeTextUnread: {
      color: colors.primary,
    },
    statusBadgeTextRead: {
      color: colors.secondaryText,
    },
    messageText: {
      color: colors.text,
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '500',
    },
    markAsReadButton: {
      marginTop: 12,
      alignSelf: 'flex-start',
      borderRadius: 999,
      backgroundColor: colors.primary,
      borderWidth: 1,
      borderColor: colors.primary,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    markAsReadButtonText: {
      color: colors.primaryText,
      fontSize: 12,
      fontWeight: '700',
    },
    disabledButton: {
      opacity: 0.55,
    },
    centerState: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 24,
    },
    errorTitle: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '700',
      marginBottom: 6,
    },
    errorSubtitle: {
      color: colors.secondaryText,
      fontSize: 13,
      textAlign: 'center',
      marginBottom: 12,
    },
    retryButton: {
      borderRadius: 999,
      backgroundColor: colors.primary,
      paddingHorizontal: 16,
      paddingVertical: 10,
    },
    retryButtonText: {
      color: colors.primaryText,
      fontWeight: '700',
      fontSize: 13,
    },
    emptyStateCard: {
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      borderRadius: 18,
      paddingVertical: 28,
      paddingHorizontal: 18,
      alignItems: 'center',
      marginTop: 40,
    },
    emptyStateEmoji: {
      fontSize: 34,
      marginBottom: 8,
    },
    emptyStateTitle: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '700',
      marginBottom: 4,
    },
    emptyStateSubtitle: {
      color: colors.secondaryText,
      fontSize: 13,
      textAlign: 'center',
      lineHeight: 18,
    },
  });

export default createStyles;
