import { StyleSheet } from 'react-native';

import type { AppColors } from '../../constants/colors';

const createStyles = (colors: AppColors) =>
  StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: colors.background,
    },
    container: {
      flex: 1,
      position: 'relative',
    },
    glowOrbTop: {
      position: 'absolute',
      top: -110,
      right: -75,
      width: 280,
      height: 280,
      borderRadius: 999,
      backgroundColor: 'rgba(37, 99, 235, 0.20)',
    },
    glowOrbBottom: {
      position: 'absolute',
      bottom: -155,
      left: -100,
      width: 300,
      height: 300,
      borderRadius: 999,
      backgroundColor: 'rgba(16, 185, 129, 0.17)',
    },
    headerCard: {
      marginHorizontal: 14,
      marginTop: 10,
      marginBottom: 12,
      paddingHorizontal: 16,
      paddingVertical: 16,
      borderRadius: 26,
      backgroundColor: colors.surface,
      borderWidth: 1.5,
      borderColor: 'rgba(37, 99, 235, 0.22)',
      flexDirection: 'row',
      alignItems: 'center',
      shadowColor: '#0b3b8f',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.2,
      shadowRadius: 18,
      elevation: 7,
    },
    backButton: {
      width: 42,
      height: 42,
      borderRadius: 13,
      backgroundColor: colors.background,
      borderWidth: 1.2,
      borderColor: 'rgba(37, 99, 235, 0.20)',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
      shadowColor: '#0f172a',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.08,
      shadowRadius: 6,
      elevation: 2,
    },
    backButtonText: {
      fontSize: 24,
      color: colors.text,
      fontWeight: '700',
      marginTop: -2,
    },
    headerTextBlock: {
      flex: 1,
    },
    headerKicker: {
      fontSize: 11,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 1.2,
      color: '#0ea5e9',
      marginBottom: 3,
    },
    headerTitle: {
      fontSize: 30,
      fontWeight: '900',
      color: colors.text,
    },
    headerSubtitle: {
      marginTop: 3,
      fontSize: 12,
      lineHeight: 17,
      color: colors.secondaryText,
      fontWeight: '500',
      maxWidth: 180,
    },
    unreadCountBubble: {
      minWidth: 72,
      borderRadius: 20,
      paddingVertical: 9,
      paddingHorizontal: 11,
      backgroundColor: 'rgba(37, 99, 235, 0.13)',
      borderWidth: 1,
      borderColor: 'rgba(37, 99, 235, 0.32)',
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.18,
      shadowRadius: 10,
      elevation: 2,
    },
    unreadCountNumber: {
      fontSize: 23,
      lineHeight: 25,
      color: colors.primary,
      fontWeight: '900',
    },
    unreadCountLabel: {
      fontSize: 11,
      color: colors.secondaryText,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.7,
    },
    actionsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginHorizontal: 14,
      marginBottom: 12,
    },
    primaryActionButton: {
      flex: 1,
      borderRadius: 999,
      backgroundColor: colors.primary,
      paddingHorizontal: 16,
      paddingVertical: 11,
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.24)',
      marginRight: 10,
      alignItems: 'center',
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.24,
      shadowRadius: 10,
      elevation: 3,
    },
    primaryActionButtonText: {
      color: colors.primaryText,
      fontWeight: '800',
      fontSize: 13,
    },
    secondaryActionButton: {
      borderRadius: 999,
      borderWidth: 1,
      borderColor: 'rgba(37, 99, 235, 0.20)',
      backgroundColor: colors.surface,
      paddingHorizontal: 15,
      paddingVertical: 11,
      alignItems: 'center',
      justifyContent: 'center',
    },
    secondaryActionButtonText: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '800',
    },
    listContent: {
      paddingHorizontal: 14,
      paddingBottom: 30,
    },
    emptyListContent: {
      flexGrow: 1,
      justifyContent: 'center',
    },
    notificationCard: {
      borderRadius: 20,
      borderWidth: 1,
      borderColor: 'rgba(100, 116, 139, 0.22)',
      backgroundColor: colors.surface,
      paddingHorizontal: 15,
      paddingVertical: 14,
      marginBottom: 11,
      shadowColor: '#0f172a',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 3,
    },
    notificationCardUnread: {
      borderColor: 'rgba(37, 99, 235, 0.45)',
      backgroundColor: 'rgba(37, 99, 235, 0.07)',
    },
    cardHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 11,
    },
    cardIdentityRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexShrink: 1,
    },
    avatarBubble: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: 'rgba(148, 163, 184, 0.20)',
      borderWidth: 1,
      borderColor: 'rgba(100, 116, 139, 0.32)',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 11,
    },
    avatarBubbleUnread: {
      backgroundColor: 'rgba(16, 185, 129, 0.18)',
      borderColor: 'rgba(16, 185, 129, 0.45)',
    },
    avatarText: {
      color: colors.text,
      fontSize: 12,
      fontWeight: '800',
    },
    typePill: {
      borderRadius: 999,
      borderWidth: 1,
      borderColor: 'rgba(37, 99, 235, 0.20)',
      paddingHorizontal: 10,
      paddingVertical: 4,
      alignSelf: 'flex-start',
      backgroundColor: colors.background,
    },
    typePillText: {
      fontSize: 10,
      color: colors.secondaryText,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 0.75,
    },
    timestampText: {
      marginTop: 6,
      fontSize: 12,
      color: colors.secondaryText,
      fontWeight: '500',
    },
    statusBadge: {
      borderRadius: 999,
      borderWidth: 1,
      paddingHorizontal: 10,
      paddingVertical: 4,
      marginLeft: 10,
    },
    statusBadgeUnread: {
      borderColor: 'rgba(37, 99, 235, 0.40)',
      backgroundColor: 'rgba(37, 99, 235, 0.15)',
    },
    statusBadgeRead: {
      borderColor: 'rgba(100, 116, 139, 0.28)',
      backgroundColor: 'rgba(148, 163, 184, 0.14)',
    },
    statusBadgeText: {
      fontSize: 10,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 0.7,
    },
    statusBadgeTextUnread: {
      color: colors.primary,
    },
    statusBadgeTextRead: {
      color: colors.secondaryText,
    },
    messageText: {
      color: colors.text,
      fontSize: 14,
      lineHeight: 21,
      fontWeight: '500',
    },
    markAsReadButton: {
      marginTop: 13,
      alignSelf: 'flex-start',
      borderRadius: 999,
      backgroundColor: colors.primary,
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.24)',
      paddingHorizontal: 13,
      paddingVertical: 8,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.22,
      shadowRadius: 9,
      elevation: 2,
    },
    markAsReadButtonText: {
      color: colors.primaryText,
      fontSize: 12,
      fontWeight: '800',
    },
    disabledButton: {
      opacity: 0.56,
    },
    centerState: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 24,
    },
    errorTitle: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '700',
      marginBottom: 6,
    },
    errorSubtitle: {
      color: colors.secondaryText,
      fontSize: 13,
      textAlign: 'center',
      marginBottom: 12,
    },
    retryButton: {
      borderRadius: 999,
      backgroundColor: colors.primary,
      paddingHorizontal: 18,
      paddingVertical: 10,
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.24)',
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.24,
      shadowRadius: 10,
      elevation: 3,
    },
    retryButtonText: {
      color: colors.primaryText,
      fontWeight: '800',
      fontSize: 13,
    },
    emptyStateCard: {
      borderWidth: 1,
      borderColor: 'rgba(37, 99, 235, 0.18)',
      backgroundColor: colors.surface,
      borderRadius: 20,
      paddingVertical: 30,
      paddingHorizontal: 18,
      alignItems: 'center',
      marginTop: 40,
      shadowColor: '#0f172a',
      shadowOffset: { width: 0, height: 7 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 4,
    },
    emptyStateEmoji: {
      fontSize: 36,
      marginBottom: 9,
    },
    emptyStateTitle: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '700',
      marginBottom: 4,
    },
    emptyStateSubtitle: {
      color: colors.secondaryText,
      fontSize: 13,
      textAlign: 'center',
      lineHeight: 19,
    },
  });

export default createStyles;
