# Generated by Django 5.2.11 on 2026-03-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_interestcategory_interest_userinterest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
