# Generated by Django 5.2.11 on 2026-05-15 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_usermemory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMemory',
        ),
    ]
