# Generated by Django 5.2.11 on 2026-06-05 14:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0004_taskoverride_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('duration_minutes', models.PositiveIntegerField()),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_social_tasks', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_tasks', to='social_task.socialtask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialTaskParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='invited', max_length=10)),
                ('rsvp_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('social_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='social_task.socialtask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_task_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('social_task', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SocialTaskNodeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_tasks', to='social_task.socialtask')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_node_task', to='task.tasktemplate')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_tasks', to='social_task.socialtaskparticipant')),
            ],
            options={
                'unique_together': {('node', 'participant')},
            },
        ),
    ]
