import { StyleSheet, Platform } from 'react-native';
import type { AppColors } from '../../../constants/colors';

const createChatRoomDetailsStyles = (colors: AppColors) =>
  StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: colors.background,
    },
    container: {
      flex: 1,
      position: 'relative',
    },
    glowOrbTop: {
      position: 'absolute',
      top: -100,
      right: -50,
      width: 250,
      height: 250,
      borderRadius: 125,
      backgroundColor: 'rgba(37, 99, 235, 0.15)',
    },
    glowOrbBottom: {
      position: 'absolute',
      bottom: -150,
      left: -80,
      width: 300,
      height: 300,
      borderRadius: 150,
      backgroundColor: 'rgba(239, 68, 68, 0.08)',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 12,
      paddingTop: Platform.OS === 'ios' ? 12 : 24,
      justifyContent: 'space-between',
    },
    backButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border + '55',
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 2,
    },
    backIcon: {
      fontSize: 18,
      color: colors.text,
      fontWeight: '700',
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: '800',
      color: colors.text,
    },
    placeholder: {
      width: 40,
    },
    content: {
      flex: 1,
      paddingHorizontal: 20,
      paddingTop: 20,
    },
    infoCard: {
      backgroundColor: colors.surface,
      borderRadius: 24,
      padding: 24,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border + '33',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.06,
      shadowRadius: 16,
      elevation: 4,
      marginBottom: 24,
    },
    roomAvatar: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: 'rgba(37, 99, 235, 0.12)',
      borderWidth: 2,
      borderColor: 'rgba(37, 99, 235, 0.25)',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 16,
    },
    roomAvatarText: {
      fontSize: 28,
      fontWeight: '800',
      color: colors.primary,
    },
    roomName: {
      fontSize: 22,
      fontWeight: '800',
      color: colors.text,
      marginBottom: 4,
      textAlign: 'center',
    },
    roomMeta: {
      fontSize: 13,
      color: colors.secondaryText,
      fontWeight: '500',
    },
    sectionTitle: {
      fontSize: 14,
      fontWeight: '800',
      color: colors.secondaryText,
      textTransform: 'uppercase',
      letterSpacing: 1.2,
      marginBottom: 12,
      paddingHorizontal: 4,
    },
    usersList: {
      backgroundColor: colors.surface,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.border + '33',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.04,
      shadowRadius: 10,
      elevation: 2,
      overflow: 'hidden',
      marginBottom: 32,
    },
    userRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 14,
      paddingHorizontal: 16,
      borderBottomWidth: 1,
      borderBottomColor: colors.divider + '33',
    },
    userAvatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border + '55',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 14,
    },
    userAvatarText: {
      fontSize: 15,
      fontWeight: '800',
      color: colors.text,
    },
    userName: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.text,
    },
    youBadge: {
      fontSize: 11,
      fontWeight: '800',
      color: colors.primary,
      backgroundColor: 'rgba(37, 99, 235, 0.15)',
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 8,
      marginLeft: 8,
      overflow: 'hidden',
    },
    actionsContainer: {
      marginTop: 'auto',
      marginBottom: 40,
    },
    deleteButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 16,
      borderRadius: 16,
      backgroundColor: 'rgba(239, 68, 68, 0.1)',
      borderWidth: 1,
      borderColor: 'rgba(239, 68, 68, 0.3)',
      gap: 8,
    },
    deleteButtonText: {
      fontSize: 15,
      fontWeight: '800',
      color: '#ef4444',
    },
    deleteIcon: {
      fontSize: 18,
      color: '#ef4444',
      marginTop: -2,
    },
    loadingContainer: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    errorContainer: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 30,
    },
    errorText: {
      fontSize: 15,
      color: colors.secondaryText,
      textAlign: 'center',
      marginBottom: 20,
    },
    retryButton: {
      backgroundColor: colors.primary,
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 999,
    },
    retryButtonText: {
      color: '#fff',
      fontWeight: '700',
    },
  });

export default createChatRoomDetailsStyles;
