# Generated by Django 5.2.11 on 2026-06-10 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('Friend_Request', 'Friend_Request'), ('Friend_Accepted', 'Friend_Accepted'), ('Invitation', 'Invitation'), ('Report', 'Report'), ('Message', 'Message')], max_length=20)),
                ('data', models.JSONField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['receiver', 'is_read'], name='notificatio_receive_0f7d9d_idx'), models.Index(fields=['receiver', 'is_sent'], name='notificatio_receive_3d4067_idx')],
            },
        ),
    ]
