import { StyleSheet, Dimensions } from "react-native";
import type { AppColors } from "../../constants/colors";

const { width: SCREEN_WIDTH } = Dimensions.get("window");

export const createSocialTasksStyles = (colors: AppColors) =>
  StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: colors.background,
    },
    container: {
      flex: 1,
      position: "relative",
    },
    glowOrbTop: {
      position: "absolute",
      top: -115,
      right: -70,
      width: 270,
      height: 270,
      borderRadius: 999,
      backgroundColor: "rgba(37, 99, 235, 0.15)",
    },
    glowOrbBottom: {
      position: "absolute",
      bottom: -130,
      left: -80,
      width: 280,
      height: 280,
      borderRadius: 999,
      backgroundColor: "rgba(16, 185, 129, 0.12)",
    },
    header: {
      marginHorizontal: 16,
      marginTop: 10,
      marginBottom: 16,
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderRadius: 20,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 4,
    },
    headerLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    backButton: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: colors.background,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: colors.border,
    },
    backButtonText: {
      fontSize: 18,
      color: colors.text,
      fontWeight: "800",
    },
    headerTitle: {
      fontSize: 20,
      fontWeight: "800",
      color: colors.text,
    },
    headerRight: {
      fontSize: 22,
    },
    scrollContent: {
      paddingHorizontal: 16,
      paddingBottom: 120, // Leave room for massive absolute button
    },
    tabs: {
      flexDirection: "row",
      backgroundColor: colors.surface,
      borderRadius: 16,
      padding: 4,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: colors.border,
    },
    tab: {
      flex: 1,
      paddingVertical: 12,
      alignItems: "center",
      borderRadius: 12,
    },
    tabActive: {
      backgroundColor: colors.primary,
    },
    tabText: {
      fontSize: 13,
      fontWeight: "700",
      color: colors.secondaryText,
    },
    tabTextActive: {
      color: colors.primaryText,
    },
    taskListEmpty: {
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 60,
    },
    taskListEmptyText: {
      fontSize: 14,
      color: colors.secondaryText,
      fontWeight: "600",
    },
    taskCard: {
      backgroundColor: colors.surface,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 16,
      marginBottom: 12,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.04,
      shadowRadius: 8,
      elevation: 2,
    },
    cardTop: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 6,
    },
    cardTitle: {
      fontSize: 16,
      fontWeight: "700",
      color: colors.text,
      flex: 1,
      marginRight: 8,
    },
    cardDur: {
      fontSize: 11,
      fontWeight: "800",
      color: colors.primaryText,
      backgroundColor: colors.primary,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 8,
    },
    cardAuthor: {
      fontSize: 13,
      color: colors.secondaryText,
      marginBottom: 8,
    },
    cardRsvpMeta: {
      fontSize: 11,
      fontWeight: "700",
      color: colors.secondaryText,
      marginBottom: 6,
    },
    progressBar: {
      height: 6,
      backgroundColor: colors.background,
      borderRadius: 3,
      overflow: "hidden",
      marginTop: 6,
      borderWidth: 0.5,
      borderColor: colors.border,
    },
    progressFill: {
      height: "100%",
      backgroundColor: colors.primary,
    },
    bottomActionBar: {
      position: "absolute",
      bottom: 24,
      left: 0,
      right: 0,
      paddingHorizontal: 16,
      zIndex: 100,
    },
    btnCreateMassive: {
      backgroundColor: colors.primary,
      borderRadius: 20,
      paddingVertical: 16,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.25,
      shadowRadius: 16,
      elevation: 6,
    },
    btnCreateMassiveText: {
      color: colors.primaryText,
      fontSize: 16,
      fontWeight: "800",
    },
    sectionLabel: {
      fontSize: 12,
      fontWeight: "800",
      color: colors.secondaryText,
      textTransform: "uppercase",
      letterSpacing: 0.5,
      marginTop: 20,
      marginBottom: 8,
    },
    detailBox: {
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 16,
      padding: 16,
      marginBottom: 12,
    },
    flexRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    flexRowLast: {
      borderBottomWidth: 0,
      paddingBottom: 0,
    },
    flexRowText: {
      fontSize: 14,
      color: colors.text,
      fontWeight: "600",
    },
    flexRowValue: {
      fontSize: 14,
      color: colors.text,
      fontWeight: "700",
    },
    badge: {
      fontSize: 10,
      fontWeight: "800",
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 8,
      textTransform: "uppercase",
    },
    bgGreen: {
      backgroundColor: "#D1FAE5",
      color: "#065F46",
    },
    bgOrange: {
      backgroundColor: "#FEF3C7",
      color: "#92400E",
    },
    bgDanger: {
      backgroundColor: "#FEE2E2",
      color: "#991B1B",
    },
    formGroup: {
      marginBottom: 16,
    },
    formInput: {
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 15,
      color: colors.text,
      fontWeight: "500",
    },
    btnPrimary: {
      backgroundColor: colors.primary,
      borderRadius: 16,
      paddingVertical: 16,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 10,
    },
    btnPrimaryText: {
      color: colors.primaryText,
      fontSize: 15,
      fontWeight: "700",
    },
    btnSecondary: {
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 16,
      paddingVertical: 16,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 10,
    },
    btnSecondaryText: {
      color: colors.text,
      fontSize: 15,
      fontWeight: "700",
    },
    btnDanger: {
      backgroundColor: colors.buttonDanger ?? colors.error,
      borderRadius: 16,
      paddingVertical: 16,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 10,
    },
    btnDangerText: {
      color: colors.primaryText,
      fontSize: 15,
      fontWeight: "700",
    },
    btnHalfContainer: {
      flexDirection: "row",
      gap: 10,
      marginBottom: 10,
    },
    btnHalf: {
      flex: 1,
    },
    listSelector: {
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 16,
      overflow: "hidden",
    },
    listItem: {
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    listItemText: {
      fontSize: 15,
      fontWeight: "600",
      color: colors.text,
    },
    checkbox: {
      width: 22,
      height: 22,
      borderRadius: 6,
      borderWidth: 2,
      borderColor: colors.border,
      alignItems: "center",
      justifyContent: "center",
    },
    checkboxChecked: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    checkboxText: {
      color: colors.primaryText,
      fontSize: 12,
      fontWeight: "800",
    },
    detailText: {
      fontSize: 15,
      color: colors.secondaryText,
      fontWeight: "500",
      lineHeight: 22,
      marginBottom: 16,
    },
    inlineSubtaskForm: {
      marginTop: 12,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      borderStyle: "dashed",
    },
    inlineSubtaskInput: {
      marginBottom: 8,
      paddingVertical: 8,
      paddingHorizontal: 10,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      fontSize: 13,
      color: colors.text,
    },
    dateTimeRow: {
      flexDirection: "row",
      gap: 5,
      width:230,
    },
    dateTimeBtn: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.surface,
      paddingVertical: 14,
      paddingHorizontal: 12,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 1,
    },
    dateTimeIcon: {
      fontSize: 18,
      marginRight: 8,
    },
    dateTimeText: {
      color: colors.primary,
      fontSize: 15,
      fontWeight: "700",
      marginTop: 2,
    },
    dateTimeLabel: {
      fontSize: 11,
      color: colors.secondaryText,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.5,
      textAlign: "center",
    },
    searchInput: {
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 15,
      color: colors.text,
      fontWeight: "500",
      marginBottom: 8,
    },
  });
