# Generated by Django 5.2.11 on 2026-03-12 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('choice_id_string', models.CharField(help_text="e.g., 'choice_1'", max_length=50)),
                ('actions_payload', models.JSONField(help_text='The raw actions array proposed by the AI.')),
                ('is_executed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(help_text='The AI message that proposed this choice.', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='ai_chat.message')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]