# Generated by Django 5.2.11 on 2026-03-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0004_alter_message_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichoice',
            name='task_snapshot',
            field=models.JSONField(blank=True, help_text='Snapshot of the relevant task(s) with 1-month overrides at the time the choice was proposed.', null=True),
        ),
    ]
