# Generated by Django 5.2.11 on 2026-03-19 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0005_aichoice_task_snapshot'),
    ]

    operations = [
    ]
