# Generated by Django 5.2.11 on 2026-03-22 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0006_add_task_snapshot_to_aichoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aichoice',
            name='task_snapshot',
        ),
    ]
