# Generated by Django 5.2.11 on 2026-04-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0007_remove_aichoice_task_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='voice_duration_seconds',
            field=models.FloatField(blank=True, help_text='Duration of the voice message in seconds.', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='voice_mime_type',
            field=models.CharField(blank=True, help_text='MIME type of the uploaded voice file (e.g. audio/webm, audio/m4a).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='voice_s3_key',
            field=models.CharField(blank=True, help_text='S3 object key for the voice recording.', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
