# Generated by Django 5.2.11 on 2026-05-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0008_add_voice_fields_to_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='voice_mood',
            field=models.JSONField(blank=True, help_text='Mood analysis result from acoustic features of the voice message. Contains: mood label, confidence, raw feature dict, and ai_hint string.', null=True),
        ),
    ]
