import { StyleSheet } from "react-native";
import { AppColors } from "../../constants/colors";

export const createStyles = (colors: AppColors) => StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: colors.background,
  },
  header: {
    fontSize: 28,
    fontWeight: "bold",
    color: colors.text,
    marginBottom: 20,
  },
  label: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.secondaryText,
    marginBottom: 8,
    marginTop: 15,
  },
  input: {
    backgroundColor: colors.surface,
    color: colors.text,
    padding: 12,
    borderRadius: 12,
  },
  categoriesScroll: {
    marginBottom: 4,
    maxHeight: 44,
  },
  categoriesScrollContent: {
    gap: 10,
  },
  categoryChip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  categoryChipSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  categoryChipText: {
    fontSize: 14,
    fontWeight: "500",
    color: colors.text,
  },
  categoryChipTextSelected: {
    color: colors.primaryText,
  },
  priorityContainer: { flexDirection: "row", marginTop: 5 },
  priorityBtn: {
    padding: 10,
    borderRadius: 12,
    backgroundColor: colors.surface,
    marginRight: 10,
  },
  prioritySelected: { backgroundColor: "#FACC15" },
  priorityText: { color: colors.text, fontWeight: "600" },
  dateBtn: {
    backgroundColor: colors.surface,
    padding: 12,
    borderRadius: 12,
  },
  dateText: { color: colors.text },
  reminderContainer: { flexDirection: "row", flexWrap: "wrap", marginTop: 5, gap: 8 },
  reminderBtn: {
    padding: 10,
    borderRadius: 12,
    backgroundColor: colors.surface,
    marginBottom: 4,
  },
  reminderSelected: { backgroundColor: "#22C55E" },
  reminderText: { color: colors.text },
  weekdayContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
    marginBottom: 4,
  },
  weekdayChip: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  weekdayChipSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  weekdayChipText: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.secondaryText,
  },
  weekdayChipTextSelected: {
    color: colors.primaryText,
    fontWeight: "700",
  },
  weekdayTimeRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 12,
    marginTop: 8,
    gap: 10,
  },
  weekdayTimeLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.text,
    width: 40,
  },
  weekdayTimeToggle: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
  },
  weekdayTimeToggleActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  weekdayTimeToggleText: {
    fontSize: 12,
    fontWeight: "500",
    color: colors.secondaryText,
  },
  weekdayTimeToggleTextActive: {
    color: colors.primaryText,
  },
  weekdayTimeValue: {
    flex: 1,
    fontSize: 14,
    color: colors.text,
    textAlign: "right",
  },
  inlineRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
    gap: 10,
  },
  smallInput: {
    flex: 1,
    backgroundColor: colors.surface,
    color: colors.text,
    padding: 12,
    borderRadius: 12,
  },
  addBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  addBtnText: { color: colors.primaryText, fontSize: 22, fontWeight: "bold" },
  emojiContainer: { flexDirection: "row", flexWrap: "wrap", marginTop: 5 },
  emojiTabsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 5,
  },
  emojiTab: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: colors.surface,
    marginRight: 10,
    marginBottom: 10,
  },
  emojiTabActive: { backgroundColor: colors.primary },
  emojiTabText: { color: colors.secondaryText, fontWeight: "600" },
  emojiTabTextActive: { color: colors.primaryText },
  emojiBtn: {
    padding: 12,
    borderRadius: 12,
    backgroundColor: colors.surface,
    marginRight: 10,
    marginBottom: 10,
  },
  emojiSelected: { backgroundColor: "#F472B6" },
  emojiText: { fontSize: 20 },
  saveBtn: {
    backgroundColor: colors.primary,
    padding: 16,
    borderRadius: 16,
    marginTop: 20,
    alignItems: "center",
  },
  saveText: { color: colors.primaryText, fontWeight: "bold", fontSize: 16 },

  scrollContent: {
    paddingBottom: 120,
  },
});

export default createStyles;