import { StyleSheet } from 'react-native';
import type { AppColors } from '../../constants/colors';

const createChatRoomsStyles = (colors: AppColors) =>
  StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: colors.background,
    },
    container: {
      flex: 1,
      position: 'relative',
    },
    glowOrbTop: {
      position: 'absolute',
      top: -115,
      right: -70,
      width: 270,
      height: 270,
      borderRadius: 999,
      backgroundColor: 'rgba(37, 99, 235, 0.20)',
    },
    glowOrbBottom: {
      position: 'absolute',
      bottom: -130,
      left: -80,
      width: 280,
      height: 280,
      borderRadius: 999,
      backgroundColor: 'rgba(16, 185, 129, 0.16)',
    },
    header: {
      marginHorizontal: 14,
      marginTop: 10,
      marginBottom: 14,
      paddingHorizontal: 18,
      paddingVertical: 18,
      borderRadius: 26,
      backgroundColor: colors.surface,
      borderWidth: 1.5,
      borderColor: 'rgba(37, 99, 235, 0.22)',
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      shadowColor: '#0b3b8f',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.2,
      shadowRadius: 18,
      elevation: 7,
    },
    kicker: {
      fontSize: 11,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 1.2,
      color: '#0ea5e9',
      marginBottom: 4,
    },
    title: {
      fontSize: 32,
      fontWeight: '900',
      color: colors.text,
    },
    subtitle: {
      marginTop: 5,
      fontSize: 13,
      lineHeight: 18,
      color: colors.secondaryText,
      fontWeight: '500',
    },
    headerActions: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingTop: 6,
      gap: 8,
    },
    newChatButton: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.24)',
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.3,
      shadowRadius: 10,
      elevation: 4,
    },
    newChatIcon: {
      fontSize: 24,
      color: colors.primaryText,
      fontWeight: '700',
      marginTop: -1,
    },

    /* ──── search modal ──── */
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.55)',
      justifyContent: 'flex-end',
    },
    modalSheet: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      paddingTop: 12,
      paddingHorizontal: 18,
      paddingBottom: 30,
      maxHeight: '75%',
      minHeight: 350,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -8 },
      shadowOpacity: 0.15,
      shadowRadius: 20,
      elevation: 10,
    },
    modalHandle: {
      width: 40,
      height: 5,
      borderRadius: 3,
      backgroundColor: colors.border,
      alignSelf: 'center',
      marginBottom: 16,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: '800',
      color: colors.text,
      marginBottom: 14,
    },
    searchInput: {
      backgroundColor: colors.background,
      borderRadius: 16,
      paddingHorizontal: 16,
      paddingVertical: 12,
      fontSize: 15,
      color: colors.text,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 14,
    },
    searchResultRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 12,
      paddingHorizontal: 4,
      borderBottomWidth: 1,
      borderBottomColor: colors.divider + '33',
    },
    searchAvatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: 'rgba(37, 99, 235, 0.15)',
      borderWidth: 1,
      borderColor: 'rgba(37, 99, 235, 0.30)',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    searchAvatarText: {
      fontSize: 14,
      fontWeight: '800',
      color: colors.primary,
    },
    searchName: {
      flex: 1,
      fontSize: 15,
      fontWeight: '700',
      color: colors.text,
    },
    searchEmail: {
      fontSize: 12,
      color: colors.secondaryText,
      marginTop: 2,
    },
    searchStartButton: {
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: colors.primary,
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.24)',
    },
    searchStartText: {
      fontSize: 12,
      fontWeight: '800',
      color: colors.primaryText,
    },
    searchEmpty: {
      paddingVertical: 30,
      alignItems: 'center',
    },
    searchEmptyText: {
      fontSize: 14,
      color: colors.secondaryText,
    },
    searchingIndicator: {
      paddingVertical: 24,
      alignItems: 'center',
    },

    /* ──── rooms list ──── */
    listContainer: {
      paddingHorizontal: 14,
      paddingBottom: 28,
    },
    roomCard: {
      flexDirection: 'row',
      alignItems: 'center',
      borderRadius: 20,
      borderWidth: 1,
      borderColor: 'rgba(37, 99, 235, 0.14)',
      backgroundColor: colors.surface,
      paddingHorizontal: 14,
      paddingVertical: 14,
      marginBottom: 10,
      shadowColor: '#0f172a',
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.08,
      shadowRadius: 10,
      elevation: 3,
    },
    roomAvatar: {
      width: 52,
      height: 52,
      borderRadius: 26,
      backgroundColor: 'rgba(37, 99, 235, 0.12)',
      borderWidth: 1.5,
      borderColor: 'rgba(37, 99, 235, 0.25)',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 14,
    },
    roomAvatarText: {
      fontSize: 16,
      fontWeight: '800',
      color: colors.primary,
    },
    roomInfo: {
      flex: 1,
    },
    roomName: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 3,
    },
    roomLastMsg: {
      fontSize: 13,
      color: colors.secondaryText,
      lineHeight: 18,
    },
    roomMeta: {
      alignItems: 'flex-end',
      marginLeft: 10,
    },
    roomTime: {
      fontSize: 11,
      color: colors.secondaryText,
      fontWeight: '600',
    },

    /* ──── empty & loading ──── */
    loadingState: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    emptyState: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 30,
    },
    emptyIcon: {
      fontSize: 54,
      marginBottom: 14,
    },
    emptyTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 6,
      textAlign: 'center',
    },
    emptySubtitle: {
      fontSize: 14,
      color: colors.secondaryText,
      textAlign: 'center',
      lineHeight: 20,
      marginBottom: 20,
    },
    emptyButton: {
      borderRadius: 999,
      backgroundColor: colors.primary,
      paddingHorizontal: 24,
      paddingVertical: 12,
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.20)',
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.24,
      shadowRadius: 10,
      elevation: 3,
    },
    emptyButtonText: {
      color: colors.primaryText,
      fontSize: 14,
      fontWeight: '800',
    },
  });

export default createChatRoomsStyles;
