import { StyleSheet } from 'react-native';
import type { AppColors } from '../../constants/colors';

const createChatRoomsStyles = (colors: AppColors) =>
  StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: colors.background,
    },
    container: {
      flex: 1,
      position: 'relative',
    },
    glowOrbTop: {
      position: 'absolute',
      top: -115,
      right: -70,
      width: 270,
      height: 270,
      borderRadius: 999,
      backgroundColor: colors.primaryLight,
      opacity: 0.8,
    },
    glowOrbBottom: {
      position: 'absolute',
      bottom: -130,
      left: -80,
      width: 280,
      height: 280,
      borderRadius: 999,
      backgroundColor: colors.primaryLight,
      opacity: 0.6,
    },
    header: {
      marginHorizontal: 20,
      marginTop: 20,
      marginBottom: 20,
      paddingHorizontal: 24,
      paddingVertical: 24,
      borderRadius: 32,
      backgroundColor: colors.surface,
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.05,
      shadowRadius: 20,
      elevation: 7,
    },
    kicker: {
      fontSize: 12,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 1.2,
      color: colors.primary,
      marginBottom: 6,
    },
    title: {
      fontSize: 32,
      fontWeight: '900',
      color: colors.text,
    },
    subtitle: {
      marginTop: 6,
      fontSize: 14,
      lineHeight: 20,
      color: colors.secondaryText,
      fontWeight: '500',
    },
    headerActions: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingTop: 8,
      gap: 10,
    },
    newChatButton: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
      elevation: 4,
    },
    newChatIcon: {
      fontSize: 28,
      color: '#FFFFFF',
      fontWeight: '700',
      marginTop: -2,
    },

    /* ──── search modal ──── */
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.4)',
      justifyContent: 'flex-end',
    },
    modalSheet: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: 36,
      borderTopRightRadius: 36,
      paddingTop: 16,
      paddingHorizontal: 24,
      paddingBottom: 40,
      maxHeight: '75%',
      minHeight: 400,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -10 },
      shadowOpacity: 0.1,
      shadowRadius: 24,
      elevation: 10,
    },
    modalHandle: {
      width: 48,
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.border,
      alignSelf: 'center',
      marginBottom: 20,
    },
    modalTitle: {
      fontSize: 22,
      fontWeight: '800',
      color: colors.text,
      marginBottom: 16,
    },
    searchInput: {
      backgroundColor: colors.background,
      borderRadius: 20,
      paddingHorizontal: 20,
      paddingVertical: 14,
      fontSize: 15,
      color: colors.text,
      marginBottom: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.04,
      shadowRadius: 10,
      elevation: 2,
    },
    searchResultRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 14,
      paddingHorizontal: 8,
      borderBottomWidth: 1,
      borderBottomColor: colors.divider + '33',
    },
    searchAvatar: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: colors.primaryLight,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 14,
    },
    searchAvatarText: {
      fontSize: 16,
      fontWeight: '800',
      color: colors.primaryDark,
    },
    searchName: {
      flex: 1,
      fontSize: 16,
      fontWeight: '800',
      color: colors.text,
    },
    searchEmail: {
      fontSize: 13,
      color: colors.secondaryText,
      marginTop: 2,
      fontWeight: '500',
    },
    searchStartButton: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 999,
      backgroundColor: colors.primary,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 3,
    },
    searchStartText: {
      fontSize: 13,
      fontWeight: '800',
      color: '#FFFFFF',
    },
    searchEmpty: {
      paddingVertical: 40,
      alignItems: 'center',
    },
    searchEmptyText: {
      fontSize: 15,
      color: colors.secondaryText,
      fontWeight: '500',
    },
    searchingIndicator: {
      paddingVertical: 32,
      alignItems: 'center',
    },

    /* ──── rooms list ──── */
    listContainer: {
      paddingHorizontal: 20,
      paddingBottom: 40,
    },
    roomCard: {
      flexDirection: 'row',
      alignItems: 'center',
      borderRadius: 24,
      backgroundColor: colors.surface,
      paddingHorizontal: 16,
      paddingVertical: 16,
      marginBottom: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.04,
      shadowRadius: 12,
      elevation: 3,
    },
    roomAvatar: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: colors.primaryLight,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 16,
    },
    roomAvatarText: {
      fontSize: 18,
      fontWeight: '800',
      color: colors.primaryDark,
    },
    roomInfo: {
      flex: 1,
    },
    roomName: {
      fontSize: 16,
      fontWeight: '800',
      color: colors.text,
      marginBottom: 4,
    },
    roomLastMsg: {
      fontSize: 14,
      color: colors.secondaryText,
      lineHeight: 20,
      fontWeight: '500',
    },
    roomMeta: {
      alignItems: 'flex-end',
      marginLeft: 12,
    },
    roomTime: {
      fontSize: 12,
      color: colors.secondaryText,
      fontWeight: '600',
    },

    /* ──── empty & loading ──── */
    loadingState: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    emptyState: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 32,
    },
    emptyIcon: {
      fontSize: 64,
      marginBottom: 16,
    },
    emptyTitle: {
      fontSize: 22,
      fontWeight: '800',
      color: colors.text,
      marginBottom: 8,
      textAlign: 'center',
    },
    emptySubtitle: {
      fontSize: 15,
      color: colors.secondaryText,
      textAlign: 'center',
      lineHeight: 22,
      marginBottom: 24,
      fontWeight: '500',
    },
    emptyButton: {
      borderRadius: 999,
      backgroundColor: colors.primary,
      paddingHorizontal: 28,
      paddingVertical: 14,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
      elevation: 4,
    },
    emptyButtonText: {
      color: '#FFFFFF',
      fontSize: 15,
      fontWeight: '800',
    },
  });

export default createChatRoomsStyles;
