# Generated by Django 5.2.11 on 2026-02-23 10:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_interestcategory_interest_userinterest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='none', max_length=10)),
                ('emoji', models.CharField(blank=True, default='', max_length=8)),
                ('start_datetime', models.DateTimeField(help_text='When the task starts, or the FIRST instance of a series.')),
                ('reminder_date', models.DateTimeField(blank=True, help_text='Optional reminder date for the task.', null=True)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Duration of the task in minutes.', null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('rrule', models.CharField(blank=True, help_text="The recurrence rule. e.g., 'FREQ=DAILY;UNTIL=20301231T235959Z'", max_length=255, null=True)),
                ('timezone', models.CharField(default='UTC', help_text="e.g., 'Africa/Cairo'", max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('categories', models.ManyToManyField(blank=True, related_name='tasks', to='user.interestcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instance_datetime', models.DateTimeField(help_text='The exact timestamp this specific instance was originally scheduled for.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('RESCHEDULED', 'Rescheduled'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('new_datetime', models.DateTimeField(blank=True, help_text="Used only if status is 'RESCHEDULED'.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='task.tasktemplate')),
            ],
            options={
                'indexes': [models.Index(fields=['task', 'instance_datetime'], name='task_taskov_task_id_d77832_idx')],
                'unique_together': {('task', 'instance_datetime')},
            },
        ),
    ]
