# Generated by Django 5.2.11 on 2026-02-23 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasktemplate',
            old_name='reminder_date',
            new_name='reminder_time',
        ),
    ]
