# Generated by Django 5.2.11 on 2026-02-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_reminder_date_tasktemplate_reminder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskoverride',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='reminder_time',
            field=models.IntegerField(blank=True, help_text='Minutes before the task starts to trigger a reminder.', null=True),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
