# Generated by Django 5.2.11 on 2026-03-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_taskoverride_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskoverride',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes for this task override', null=True),
        ),
    ]
