# Generated by Django 5.2.11 on 2026-06-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_taskoverride_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktemplate',
            name='timezone',
            field=models.CharField(default='Africa/Cairo', help_text="e.g., 'Africa/Cairo'", max_length=64),
        ),
    ]
